:PROPERTIES:
:ID:       0d98d9d9-02e0-4096-9015-a710fc068843
:END:
#+title: Guix
#+author: Javier Pacheco
#+description: How to install GNU/Guix without the libre software thing.
#+tags: :guix:linux:
#+date: [2024-12-24 Tue 13:24]

* About.
The script =install.sh= will do a couple of actions to try to make the GNU/guix installation more friendly, so, basically this =README.org= file will tangle the script, the power of emacs of course. So, while I was working in this "note" file, then I realized that I can use emacs and make a script.

* Download and burn the iso.
I use the systemcrafter [[https://github.com/SystemCrafters/guix-installer][ISO.]]

#+begin_src shell
sudo dd status=progress if=guix-installer-202106150234.iso of=/dev/sdb && sync
#+end_src

* Install the OS by hand.
Now with the Guix iso. Boot your laptop in it, and follow the instructions to install the OS, just ignore the warnings about the libre software, And stop in the part that you actually going to start the installation, and open another TTY:

#+begin_src shell
Ctrl + Alt + f2  
#+end_src
** Initialize the guix daemon.
We need to start the daemon to start the process and point it to the mount partition to start the installation there.

#+begin_src shell
herd start cow-store /mnt
#+end_src
** Copy the channels.scm file from the ISO to our new system.

#+begin_src shell
cp /etc/channels.scm /mnt/etc && chmod +w /mnt/etc/channels.scm
#+end_src

** Modify the config.scm file using patch

#+begin_src shell
cp /mnt/etc/config.scm .

sed -i '/(use-modules (gnu))/s/$/ (nongnu packages linux)/' config.scm
sed -i '/(operating-system/a\
  (kernel linux)\
  (firmware (list linux-firmware))' config.scm
#+end_src

** The final command:

#+begin_src shell
guix time-machine -C /mnt/etc/channels.scm -- system init /mnt/etc/config.scm /mnt
#+end_src


* The script itself "Automated":

#+begin_src shell :tangle ./install.sh :shebang "#!/bin/sh"
set -e
set -o pipefail

log_error() {
	echo "$(date '+%Y-%m-%d %H:%M:%S') - ERROR: $1" >&2
	exit 1
}

log() {
	echo "$(date '+%Y-%m-%d %H:%M:%S') - $1"
}

log "Starting cow-store service..." && herd start cow-store /mnt || log_error "Failed to start cow-store."
log "Copying channels.scm..." && cp /etc/channels.scm /mnt/etc && chmod +w /mnt/etc/channels.scm || log_error "Failed to copy or modify channels.scm."
log "Copying config.scm..." && cp /mnt/etc/config.scm ./config.scm || log_error "Failed to copy config.scm."
log "Updating config.scm with sed..." && \
	sed -i 's/(use-modules (gnu))/(use-modules (gnu) (nongnu packages linux))/' ./config.scm && \
	sed -i '/(operating-system/a\
  (kernel linux)\
  (firmware (list linux-firmware))' ./config.scm || log_error "Failed to update config.scm."
log "Copying updated config.scm back to /mnt/etc..." && cp ./config.scm /mnt/etc/config.scm || log_error "Failed to copy updated config.scm back to /mnt/etc."
log "Initializing system with guix time-machine..." && guix time-machine -C /mnt/etc/channels.scm -- system init /mnt/etc/config.scm /mnt || log_error "System initialization failed."
log "Clean this folder..." && rm ./config.scm 

log "Script completed successfully."
#+end_src
